######################################################################
# Automatically generated by qmake (2.01a) Per Eyl 13 20:51:31 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
TRANSLATIONS = ceviri/qpod_tr.ts
TRANSLATIONS += ceviri/qpod_en.ts  

# Input
HEADERS += qpod.h
FORMS += anaPencere.ui
SOURCES += main.cpp qpod.cpp
